### PR TITLE
pass ignore duplicate = true

### PR DESCRIPTION
**Pull request by bradfordcondon**
see #110 for why this is desired.

### CODE REVIEW

**Comment by bradfordcondon** [comment]
on second thought my understanding is you dont want to ignore duplicates for invoke_workflow, just for check_workflow.  updated hte PR to reflect this.


```php
 $job_id = tripal_add_job("Galaxy Workflow #" . $sid, 'tripal_galaxy',
      'tripal_galaxy_invoke_workflow', $args, $user->uid, 10, $includes, $ignore_duplicates= FALSE);
```

**Comment by bradfordcondon** [comment]
pinging this PR.  Our sites get filed without thousands of these jobs when a long job runs.

**Comment by spficklin** [comment]
Hi @bradfordcondon sorry that took so long.  Just a simple change that makes sense.  @shawnawsu indicated she tested it so merging now.

**Comment by MingChen0919** [comment]
hi @bradfordcondon and @spficklin, the "checking workflow status' cron job is not running repeatedly as before. I was wondering if this is caused by this PR. My understanding is that `$ignore_duplicates` should be se `TRUE` because we need to check workflow status periodically.

**Comment by bradfordcondon** [comment]
Hi @MingChen0919 the job should still be running repeatedly, it just shouldnt spawn a new job when the previous job has not run yet.  see #110 .  

You're saying that new cron jobs are not submitted, period?

Would you please create a new issue referencing this PR so we can fix?

**Comment by bradfordcondon** [comment]
this is waht the jobs class does:

```php
 try {
      // Before inserting a new record, and if ignore_duplicate is TRUE then
      // check to see if the job already exists.
      if ($details['ignore_duplicate'] === TRUE) {
        $query = db_select('tripal_jobs', 'tj');
        $query->fields('tj', array('job_id'));
        $query->condition('job_name', $details['job_name']);
        $query->isNull('start_time');
        $job_id = $query->execute()->fetchField();
        if ($job_id) {
          $this->load($job_id);
          return FALSE;
        }
      }
```

so in theory it is only a problem if a job already exists with that name, whose start_time is null.

as i said please create a new issue so we can discuss there.  While we're talking the documentation on ignore_duplicate is inconsistent and needs to be fixed so i ned ot make a core issue for that either way.  (the jobs class says the default is true, when the default is false).

**Comment by MingChen0919** [comment]
sorry @bradfordcondon , I think I was wrong. I submitted several workflows. The "checking workflow" cron jobs for those workflows actually successfully completed. For some reason they were invoked a couple hours later after the jobs were complete. And now it seems normal.

**Pull request merged**
