### PR TITLE
fix default value issues for conditional inputs

### PR DESCRIPTION
**Pull request by MingChen0919**
Default values for conditional inputs are messed up, especially for nested conditional inputs (conditional inputs within another conditional inputs). This PR is a fix for this issue.

Before fixed:

wrong-default-values

After fixed

fixed-default-values

**The idea behind the fix**:

Since a conditional input is a "select" type input, and its value is pre-defined be the workflow creator, users are not allowed to change its value, I removed all unselected option items for conditional input. Users will only see one option for a drop-down list for conditional input, I add description to indicate conditional inputs (see below):
screen shot 2018-05-21 at 5 13 31 pm

Issues about **Optional Settings** fieldset:
Adding an **Optional Settings** fieldset to group **fixed_value** inputs also messes up the default values. I remove this part. I don't use a fixed value fieldset, either. That means the PR #88 is discarded.

**So, this PR 1) fixes default value issues for conditional inputs, 2) discards the "Optional Settings" fieldset implementation; 3) discards PR #88, and therefore the workflow webform will have exactly the same structure and inputs order as it appears in the Galaxy server.**

Here is a workflow for testing: https://galaxy.bioinfo.wsu.edu/u/mingchen0919/w/test-default-values-for-conditional-inputs.

### CODE REVIEW

**Comment by spficklin** [comment]
HI @MingChen0919 I have loaded the mapping-histat2-single-end workflow (from here: https://github.com/statonlab/galaxy-workflows/blob/master/mapping-hisat2-single-end.ga) to try and review this pull request but on step 6 I do not see the same Advanced Options that you show in the screen shot above.  The "Spliced alignment options" dropdown for me only has one option " Use default values".   I also don't have the "Upload a new file" fieldset under the GTF file option.  Am I using the same workflow?

Also, I think I prefer the previous method that just shows text that says "Use default values" rather than the select box.  The select box makes me think I can change it and then I click it to see what other options I have and there are none.   I also find the wording below the text box confusing.   For example the first sentence "This is a conditional Input".  For a user that knows nothing about Galaxy or how the workflow is configured that sentence makes no sense.   My preference would be to get rid of the drop down and the description, and go back to a single text.  We can rewrite that text however to say something like "This option has been preset to use default values and cannot be changed".

**Comment by mestato** [comment]
I agree with Stephen, the text "This option has been preset to use default values and cannot be changed" will make more sense to users. And no drop down selection.

**Comment by MingChen0919** [comment]
I agree that the description is confusing and I could have a better one. 

I also agree that making "Use default values" a *fixed value* instead of a *dropdown list* makes more sense when you cannot change its value for a conditional input. However, there is bug here. Here "Use default values" is just an option from a conditional input, it really doesn't mean it is using the preset value in the workflow.

I'll use the conditional input in my previous comment as an example:
So **spliced alignment options** is a conditional input which Has two options: "Use the default values" and "Specify spliced alignment options".  Even though in my workflow, the actual option i have selected is "Specify spliced alignment options". In my tripal site, the tripal galaxy module still select the "Use the default values" option, which will hide all advanced options.

**The webform in the tripal site always use the first option instead of the actual, correct option from a conditional input dropdown list.** 

Please use the workflow I posted on the comment for testing (attached in this comment). The workflow you used actually have all "Use default values" selected for for conditional inputs, that's why you didn't see the same advanced options.

[test-default-values-for-conditional-inputs.ga.zip](https://github.com/tripal/tripal_galaxy/files/2080843/test-default-values-for-conditional-inputs.ga.zip)

I had to make the preset value for conditional input a select type input to fix the issue I encountered. I wish I could have a better fix. But there are many recursive functions in the code and webform gets really complicated, especially when there are many levels of nested conditional inputs. This is really a challenge to me.

**Comment by spficklin** [comment]
I'm trying to update the code to get us what we want for this PR.

**Comment by spficklin** [comment]
I'm going to close out this PR because I submitted a new one #102  with all of the changes we discussed.   I found a few bugs as well that I fixed.  @MingChen0919 can you pull that new PR and test it?  If it works for you then I'll merge it in and we'll have this one done!

**Pull request closed without merging**
