### PR TITLE
fix duplicated description on input fields

### PR DESCRIPTION
**Pull request by MingChen0919**
This PR fixes issue #121 .

### CODE REVIEW

**Comment by spficklin** [comment]
Hi @MingChen0919 I cannot duplicate this issue.  I'm guessing it's a problem if the description is listed in the workflow twice?  You commented out some code related to an 'extra_description' element, but I don't think we should take that approach.  That code is there for a reason.  On Issue #121 if you can share an example workflow we can use to test and see what the best approach should be.

**Comment by MingChen0919** [comment]
Hi @spficklin , I attached a workflow to issue #121 as you requested.

**Comment by spficklin** [comment]
Waiting on question posted on issue #121.

**Comment by spficklin** [comment]
Okay, so after reviewing more closely your pull request I agree that you made the correct code changes. I'm going to approve the PR.

**Pull request merged**
