### PR TITLE
Expired links for clickable files in Aurora Tools reports.

### PR DESCRIPTION
**Pull request by spficklin**
This is a fix for issue #76.  

@MingChen0919 can you test with the workflow you provided to me and with a few others you have?

### CODE REVIEW

**Comment by MingChen0919** [comment]
Hi @spficklin , unfortunately, this PR does not work for me. It also breaks the theme of the aurora tool output.

The links do not for me.

screen shot 2018-06-09 at 12 50 01 am

The "outputs" section should be a **clickable file tree**, see the results below in galaxy. 

screen shot 2018-06-09 at 12 44 06 am

Although, the "outputs" is not a clickable file tree in both branch **7.x-1.x** and **76-expired_links**, the **76-expired_links** makes the report look even worse. 

screen shot 2018-06-09 at 12 54 30 am

**Review by MingChen0919 — COMMENTED** [review]
Unfortunately, this PR does not work for me.

**Comment by MingChen0919** [comment]
This PR fixed the expired links issue, but it breaks the theme of the report page (see the difference in the screenshots above).

here is an example output from the `test-workflow` to show how the report should look like in galaxy.

[aurora_fastqc_on_data_2_and_data_1.zip](https://github.com/tripal/tripal_galaxy/files/2096523/aurora_fastqc_on_data_2_and_data_1.zip)

the report file is `aurora_fastqc_on_data_2_and_data_1_html.html` after unzipping the file.
also, i got some errors on the result page:

```
Notice: Undefined variable: galaxy in tripal_galaxy_workflow_report() (line 896 of /var/www/html/sites/all/modules/custom_modules/tripal_galaxy/tripal_galaxy.module).
Notice: Trying to get property of non-object in tripal_galaxy_workflow_report() (line 896 of /var/www/html/sites/all/modules/custom_modules/tripal_galaxy/tripal_galaxy.module).
```

**Comment by shawnawsu** [comment]
@spficklin @MingChen0919 I can't seem to get the aurora tools to successfully install on my local galaxy server. While I wrangle with that could one of you test to see if the small change I made fixes the theme issue, it will definitely address the error issue.

**Comment by spficklin** [comment]
@MingChen0919 did Shawna's fix resolve the problem for you?

**Comment by MingChen0919** [comment]
**The workflow I used to test this PR is:**

[76-expired_links.ga.zip](https://github.com/tripal/tripal_galaxy/files/2635541/76-expired_links.ga.zip)

**This PR DID fix the expired links issue** 

The result is a little different between in Tripal and Galaxy:

The file tree in the tripal site result is automatically collapsed.

screen shot 2018-11-30 at 9 52 24 pm

**Below is what it looks like in Galaxy**:

screen shot 2018-11-30 at 9 51 51 pm

**Comment by spficklin** [comment]
Hi @MingChen0919 when you say "The file tree in the tripal site result is automatically collapsed" do you mean the display is still not working for you?  Or is a collapsed file tree okay?

**Comment by MingChen0919** [comment]
The display works for me and all the links work. A collapsed file tree is okay. By default aurora tools display an uncollapsed tree. I don't know why the file tree is expanded when it is being viewed from within Tripal.

**Comment by MingChen0919** [comment]
I think we can merge this PR, since it does fix the expire links issue. If we want to fix the file tree display problem, we can open a new issue.

**Pull request merged**
