### PR TITLE
Group fixed value inputs

### PR DESCRIPTION
**Pull request by MingChen0919**
Instead of grouping fields that have optional values into a optional settings fieldset, this PR group fixed value input fields into a 'fixed value inputs' fieldset. It makes more sense to me since users won't need to or can't change the values of these inputs.

### CODE REVIEW

**Comment by shawnawsu** [comment]
Hi Ming, 

Since I'm just acquainting myself with Galaxy I had a question about this pull request. The commit https://github.com/tripal/tripal_galaxy/pull/88/commits/4cb89c9abb089684d3f492acdc1f5f236fedeb57, removes optional settings and places fixed value fields in their place, so will workflows never have optional settings, only fixed value fields?

Thanks,
Shawna

**Comment by MingChen0919** [comment]
Hi @shawnawsu , it's possible some workflows will never have optional settings. However, the original code creates an optional settings fieldset at each step without checking if there are any optional settings inputs. This commit groups inputs that have fixed values instead of inputs that have optional settings into a fieldset. So no matter if the workflow have optional settings or not, it won't have a optional settings fieldset any more. The fieldset will exist only when there are fixed value inputs.  

It makes more sense to put fixed value inputs into a fieldset and display optional settings inputs to users first if there is any. Because users can't change values of fixed value inputs fields. This commit does so.

**Comment by spficklin** [comment]
@MingChen0919 Can you provide a workflow I can use to test this?

**Comment by MingChen0919** [comment]
Hi @spficklin, I submitted a new PR #96. You can ignore and close this PR now.

**Pull request closed without merging**
