### PR TITLE
Fix error where variables are not defined

### PR DESCRIPTION
**Pull request by almasaeed2010**
Issue #109 

This is a simple fix to load the submission and node for use by the mail functions.

Thanks!

### CODE REVIEW

**Comment by shawnawsu** [comment]
Hi Abdullah, 

This is tricky because some issues you're addressing are fixed in #109. Can you fork that PR and fix from there?

Thanks,
Shawna

**Comment by almasaeed2010** [comment]
Oh sorry I didn't realize there was a PR there for these issues. I'll try to port it over when I can but please give me a few days to get to it. Thanks!

**Comment by shawnawsu** [comment]
If you're ok with it I can get your changes into #109. Just let me know if you'd prefer to do it yourself.

**Comment by almasaeed2010** [comment]
That would be great if you could! 

So #109 is not a PR, are you sure that’s the correct link?

**Comment by almasaeed2010** [comment]
I think you meant #119 👍 I am submitting a new PR excluding the email issues since they are fixed on that PR.

**Pull request closed without merging**
