### PR TITLE
Display annotation with markup component

### PR DESCRIPTION
**Pull request by MingChen0919**
This PR adds a markup component to each workflow step. It extracts the annotation from galaxy workflow directly and displays it at each step. With this PR, we can add instructions to each step from within Galaxy and display them on the Tripal site. The annotation accepts full HTML string.

 **Annotation from galaxy**
screen shot 2018-05-25 at 11 41 52 am

**Annotation shows on tripal site**
screen shot 2018-05-25 at 11 39 55 am

### CODE REVIEW

**Comment by spficklin** [comment]
Hi @MingChen0919 I like this addition but can you remove the harcoded "Instructions" title?  

I'm just a bit concerned that someone may use the Annotations field for something other than instructions and then it won't make sense.   Also, the h3 tag doesn't match the style of the items in the rest of the page. For example. On step 1 of the mapping-histat2-single-end the title "Data file" has different formatting.  

So my suggestion would be to remove the ```<h3>Instructions</h3>``` from the markup, and just give the component a title "Description".  I think the word "Description" matches better anything someone could put in the 'Annotation' field (including Instructions) and the word "Description" would match the style of other components on the webform.

**Comment by MingChen0919** [comment]
Hi @spficklin , maybe I am wrong, but the 'title' attribute does not work for webform markup component.

Would an additional fieldset like below work better? The fieldset only exists when annotation is available for that step.

screen shot 2018-06-07 at 1 53 53 pm

**Comment by spficklin** [comment]
I like it.  Thank you.

**Comment by spficklin** [comment]
@MingChen0919 I messed this up.  I thought you had code in this PR that generated the images you posted above, so I merged without testing.  I should have tested first.  It seems you didn't push the code that generated those images?  So, I reverted the merge.  Can you redo this pull request with the updated code?  

Sorry about that.

**Pull request merged**
